-- Esquema de base de datos para Supabase

-- Tabla de Usuarios
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabla de Proyectos
CREATE TABLE IF NOT EXISTS projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  code TEXT UNIQUE NOT NULL,
  description TEXT,
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'archived')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabla de Tareas
CREATE TABLE IF NOT EXISTS tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT REFERENCES projects(id) ON DELETE CASCADE,
  month INTEGER NOT NULL,
  week INTEGER NOT NULL,
  title TEXT,
  dynamic_data JSONB DEFAULT '{}'::jsonb,
  fotos_prl BOOLEAN DEFAULT false,
  inventario BOOLEAN DEFAULT false,
  incidencia BOOLEAN DEFAULT false,
  comentarios TEXT DEFAULT '',
  status TEXT DEFAULT 'abierta' CHECK (status IN ('abierta', 'cerrada', 'incidencia')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Índices para mejorar el rendimiento de las búsquedas
CREATE INDEX IF NOT EXISTS idx_tasks_project_id ON tasks(project_id);
CREATE INDEX IF NOT EXISTS idx_tasks_month_week ON tasks(month, week);

-- Script de actualización para asegurar que la columna 'status' existe con el valor por defecto correcto
DO $$ 
BEGIN 
  -- Asegurar columna status en tasks
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='tasks' AND column_name='status') THEN
    ALTER TABLE tasks ADD COLUMN status TEXT DEFAULT 'abierta' CHECK (status IN ('abierta', 'cerrada', 'incidencia'));
  ELSE
    -- Asegurar que tiene el check constraint si ya existe
    BEGIN
      ALTER TABLE tasks DROP CONSTRAINT IF EXISTS tasks_status_check;
      ALTER TABLE tasks ADD CONSTRAINT tasks_status_check CHECK (status IN ('abierta', 'cerrada', 'incidencia'));
    EXCEPTION
      WHEN duplicate_object THEN NULL;
    END;
  END IF;
END $$;
